language: node_js
cache: yarn
node_js:
  - '8'

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  - provider: releases
    skip_cleanup: true
    local_dir: dist/*
    api_key: $GITHUB_TOKEN
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    local_dir: examples/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
